split:
  test_size:  0.1
  val_size: 0.1
  number_random: 42

train:
  fit:
    epochs: 20
    batch_size: 32

  deep_layers:
    dense:
      count_neuron: 1
      activation: relu
  
  compile:
    optimizer: adam
    loss: mse
    metrics: [mse]

