split:
  test_size:  0.1
  val_size: 0.1
  number_random: 42

train:
  fit:
    epochs: 50
    batch_size: 64

  deep_layers:
    dense:
      count_neuron: 8
      activation: relu
    output:
      count_neuron: 1
  
  compile:
    optimizer: adam
    loss: mse
    metrics: [mae]

