split:
  test_size:  0.1
  val_size: 0.1
  number_random: 42

train:
  fit:
    epochs: 150
    batch_size: 64

  deep_layers:
    dense:
      count_neuron: 128
      activation: relu
    dense_1:
      count_neuron: 32
      activation: relu
    dense_2:
      count_neuron: 128
      activation: relu
    dense_3:
      count_neuron: 64
      activation: relu
    dropout:
      count_neuron: 0.5
    output:
      count_neuron: 1
  
  compile:
    optimizer: adam
    loss: mse
    metrics: [mae]

